### PR TITLE
PR: Handle new table format including wish type column (Nov 2021)

### PR DESCRIPTION
**Pull request by mchubby**

### CODE REVIEW

**Review by EnderSyth — APPROVED** [review]
Thanks for updating this.

**Comment by mchubby** [comment]
Fix is incomplete, format 1 (clean clipboard form, Genshin Wish Tracker) still uses the 3rd column, which is no longer the date&time but wish type instead (e.g. "Character Event Wish-2")

https://github.com/EnderSyth/Genshin-Wish-Export/blob/2eb6544f21e671ba237caaee01551df355334417/Genshin%20Wish%20Export.ps1#L77-L82


Sorry for the botched PR.

**Comment by mchubby** [comment]
<s>Also, the "Weapon|Character" regex matches both the first column and the new one e.g "Character Event Wish-2"</s>
The regex is "^($langRegex)$", matching a complete line.

**Comment by mchubby** [comment]
Use $_.Context.DisplayPostContext[2] instead of $_.Context.DisplayPostContext[1].

**Comment by EnderSyth** [comment]
Ah good catch didn't test both formats when I merged it last time so my bad as well thanks for pointing it out. Updated the code with the correct context to grab.

**Comment by mchubby** [comment]
Hmm there are more errors, I think the current release should be pulled out because it can yield erroneous results.
    $timeArray = foreach ($item in $array) { ($item | sls -Pattern "[\d- :]{19}").Matches.Value }
    $uniqueTimes = $timeArray | Get-Unique

(...)Character Event Wish-22022-02-07 22:30:45
=> gives 19-character long match "-22022-02-07 22:30:" instead of "2022-02-07 22:30:45"

**Comment by mchubby** [comment]
foreach ($item in $array) { ($item | sls -Pattern "20[\d][\d]-[\d][\d]-[\d][\d] [\d:]{8}").Matches.Value }

**Comment by EnderSyth** [comment]
I just reinstalled to test and both formats resulted in correctly formatted data for me on the output. I even double check and made a fresh sheet on Genshin Wish Tally and pasted the output manually in and it pulled out the data correctly. 

image

Mind posting the raw text from the copy so I can try checking against that?

**Pull request merged**
